# Generated by Django 3.2 on 2022-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('font_icon_code', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='banner_slider',
            name='font_icon_code',
        ),
        migrations.AddField(
            model_name='banner_slider',
            name='image',
            field=models.ImageField(default='no.jpg', upload_to='Banner_slider'),
        ),
    ]
