# Generated by Django 3.2 on 2022-03-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0002_auto_20220331_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('font_icon_code', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
