# Generated by Django 3.2 on 2022-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0003_our_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('project_type', models.CharField(max_length=50)),
                ('image', models.ImageField(default='no.jpg', upload_to='Banner_slider')),
                ('description', models.TextField()),
            ],
        ),
    ]
