# Generated by Django 3.2 on 2022-04-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0004_project_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(default='no.jpg', upload_to='Banner_slider')),
            ],
        ),
    ]
