# Generated by Django 3.2 on 2022-04-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0005_developer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer_profile',
            name='image',
            field=models.ImageField(default='no.jpg', upload_to='Developer_Profile'),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='image',
            field=models.ImageField(default='no.jpg', upload_to='Project_Gallery'),
        ),
    ]
