# Generated by Django 3.2 on 2022-04-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0006_auto_20220401_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer_profile',
            name='dribbble_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer_profile',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer_profile',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
