# Generated by Django 3.2 on 2022-04-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0009_auto_20220401_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='no.jpg', upload_to='BlogImage'),
        ),
    ]
