# Generated by Django 3.2 on 2022-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0010_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ClientsImg')),
                ('review', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
