# Generated by Django 3.2 on 2022-04-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0011_clientsreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ToolsImg')),
            ],
        ),
    ]
