# Generated by Django 3.2 on 2022-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0012_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ToolsImg')),
            ],
        ),
    ]
