# Generated by Django 3.2 on 2022-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0013_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
    ]
