# Generated by Django 3.2 on 2022-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0014_portfolio_portfolio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.URLField(),
        ),
    ]
