# Generated by Django 3.2 on 2022-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0015_alter_portfolio_portfolio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('imagr', models.ImageField(upload_to='ClientsImg')),
            ],
        ),
    ]
