# Generated by Django 3.2 on 2022-04-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0016_our_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_client',
            old_name='imagr',
            new_name='image',
        ),
    ]
