# Generated by Django 3.2 on 2022-04-04 08:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universeinfotech_app', '0017_rename_imagr_our_client_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('active_status', models.BooleanField(default=True)),
                ('job_requirement', ckeditor_uploader.fields.RichTextUploadingField()),
                ('educational_eequirements', ckeditor_uploader.fields.RichTextUploadingField()),
                ('compensation_other_benefits', ckeditor_uploader.fields.RichTextUploadingField()),
                ('experience', models.CharField(max_length=150)),
                ('salary', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('expected_salary', models.CharField(max_length=150)),
                ('cv', models.FileField(upload_to='ApplicationCV')),
                ('message', models.TextField()),
            ],
        ),
    ]
